# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: helios.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'helios.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0chelios.proto\x12\x06helios\"\x07\n\x05\x45mpty\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"2\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"\x8c\x01\n\rSystemMetrics\x12\x11\n\tcpu_usage\x18\x01 \x01(\x02\x12\x14\n\x0ctotal_memory\x18\x02 \x01(\x04\x12\x13\n\x0bused_memory\x18\x03 \x01(\x04\x12\x1c\n\x14memory_usage_percent\x18\x04 \x01(\x02\x12\x1f\n\x05\x64isks\x18\x05 \x03(\x0b\x32\x10.helios.DiskInfo\"X\n\x08\x44iskInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0btotal_space\x18\x02 \x01(\x04\x12\x12\n\nused_space\x18\x03 \x01(\x04\x12\x15\n\rusage_percent\x18\x04 \x01(\x02\"\xa4\x01\n\x15ValidateActionRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\x12;\n\x07\x63ontext\x18\x03 \x03(\x0b\x32*.helios.ValidateActionRequest.ContextEntry\x1a.\n\x0c\x43ontextEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"M\n\x16ValidateActionResponse\x12\x0f\n\x07is_safe\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x12\n\nrisk_score\x18\x03 \x01(\x02\x32\xca\x01\n\nHeliosCore\x12\x31\n\x04Ping\x12\x13.helios.PingRequest\x1a\x14.helios.PingResponse\x12\x38\n\x10GetSystemMetrics\x12\r.helios.Empty\x1a\x15.helios.SystemMetrics\x12O\n\x0eValidateAction\x12\x1d.helios.ValidateActionRequest\x1a\x1e.helios.ValidateActionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helios_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VALIDATEACTIONREQUEST_CONTEXTENTRY']._loaded_options = None
  _globals['_VALIDATEACTIONREQUEST_CONTEXTENTRY']._serialized_options = b'8\001'
  _globals['_EMPTY']._serialized_start=24
  _globals['_EMPTY']._serialized_end=31
  _globals['_PINGREQUEST']._serialized_start=33
  _globals['_PINGREQUEST']._serialized_end=63
  _globals['_PINGRESPONSE']._serialized_start=65
  _globals['_PINGRESPONSE']._serialized_end=115
  _globals['_SYSTEMMETRICS']._serialized_start=118
  _globals['_SYSTEMMETRICS']._serialized_end=258
  _globals['_DISKINFO']._serialized_start=260
  _globals['_DISKINFO']._serialized_end=348
  _globals['_VALIDATEACTIONREQUEST']._serialized_start=351
  _globals['_VALIDATEACTIONREQUEST']._serialized_end=515
  _globals['_VALIDATEACTIONREQUEST_CONTEXTENTRY']._serialized_start=469
  _globals['_VALIDATEACTIONREQUEST_CONTEXTENTRY']._serialized_end=515
  _globals['_VALIDATEACTIONRESPONSE']._serialized_start=517
  _globals['_VALIDATEACTIONRESPONSE']._serialized_end=594
  _globals['_HELIOSCORE']._serialized_start=597
  _globals['_HELIOSCORE']._serialized_end=799
# @@protoc_insertion_point(module_scope)
